version: latest

methodology: network_validation   # technique used in the validation:
                                  # - network_validation: to validate a single network file specified in    "network_validation" block

datasets:
  demand: ["ourworldindata"]  # list of datasets sources to use. A subset of 'ourworldindata'
  installed_capacity: ["irena"]  # list of datasets sources to use. A subset of 'irena'
  # energy_dispatch: []  # list of datasets sources to validate energy dispatch. Not yet supported
  # network: []  # list of datasets sources to validate networks. Not yet supported

network_validation:
  network_path: "" # File to the PyPSA network file to validate
  year: [2021]  # year of the network to validate
  countries: ['NG']  # country of the network to validate
  shapefile: False
  validate_cross_border_capacity: true # validation of cross border capacity

scenario_validation:  # scenario options: it specifies the years and countries to compare
  years: [2021]  # years to validate
  countries: [NG]  # countries to validatehe network to validate
  shapefile: False
  validate_cross_border_capacity: true # validation of cross border capacity
